version: '3'

services:
  kotlin-mail-app:
    container_name: kotlin-mail-app
    build: .
    image: kotlin-mail-app:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mailmysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306

  mailmysqldb:
    container_name: mailmysqldb
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=kotlin_mail
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
